/* Atlas de Cetrios. Coordenadas normalizadas sobre el mapa oficial incluido.
   Las jerarquías recientes sustituyen a las de index (12).html.
   Para incorporar una vista, agregá su archivo en assets y una entrada en views.
   Los archivos se sirven desde el mismo sitio, sin enlaces temporales. */
(() => {
 const view=(file,caption,alt)=>({src:'assets/'+file+'.webp',thumb:'assets/'+file+'-thumb.webp',caption,alt:alt||caption});
 const groups=[
  {id:'central',name:'Continente Central',subtitle:'El corazón de Cetrios'},
  {id:'voranor',name:'Voranor',subtitle:'Tierras del Ocaso'},
  {id:'thalkras',name:'Thalkras',subtitle:'Tierras del Sur-Oeste'},
  {id:'elyndor',name:'Elyndor',subtitle:'Tierras del Amanecer'},
  {id:'solenia',name:'Solenia',subtitle:'Tierras del Sur-Este'},
  {id:'norte',name:'Tierras del Norte',subtitle:'El extremo helado'},
  {id:'mares',name:'Islas y mares',subtitle:'Más allá de las costas'}
 ];
 const places=[
 {id:'aethrion',name:'Aethrion',group:'central',type:'capital',label:'Capital de Cetrios',x:.479,y:.467,description:'El Palacio Negro se alza en el centro de Aethrion. A su alrededor, los anillos de la ciudad, sus murallas y sus caminos forman el corazón del mundo Eco.',children:['Liedor','Cicus'],views:[view('aethrion','Aethrion · el palacio y la ciudad','Vista de Aethrion, ciudad circular con un palacio gótico central y estandartes dorados')]},
 {id:'velmor',name:'Velmor',group:'central',type:'city',label:'Ciudad del norte',x:.389,y:.294,description:'Una ciudad de piedra oscura entre bosques y montañas. El palacio de Velmor emerge de los árboles, con las Tierras Heladas en el horizonte.',children:['Pesero de Hielo'],views:[view('velmor','Velmor · ciudad y bosques del norte')]},
 {id:'darvanis',name:'Darvanis',group:'central',type:'city',label:'Ciudad',x:.349,y:.521,description:'Darvanis ocupa la costa occidental del Continente Central. Sus construcciones oscuras se extienden entre el relieve montañoso, el bosque y las rutas que llegan al mar.',children:[],views:[view('darvanis','Darvanis · la ciudad costera')]},
 {id:'bosque-korvan',name:'Bosque de Korvan',group:'central',type:'region',label:'Bosque',x:.552,y:.30,description:'Un bosque antiguo al noreste de Aethrion. Entre sus árboles se abre el Claro del Eco, rodeado por un anillo de vegetación y una luz que destaca entre la bruma.',children:['Claro del Eco'],views:[view('korvan','El Claro del Eco'),view('korvan-panorama','Korvan · panorama del bosque')]},
 {id:'lagos-eldra',name:'Lagos de Eldra',group:'central',type:'region',label:'Región lacustre',x:.387,y:.639,description:'Las aguas de Eldra conectan sus poblaciones y puertos entre penínsulas, islas y bosques. Puerto de Eldra y Puerto de Inlet forman parte de esta región.',children:['Puerto de Eldra','Puerto de Inlet'],views:[view('eldra','Lagos de Eldra · sus ciudades y puertos')]},
 {id:'valle-arden',name:'Valle de Arden',group:'central',type:'region',label:'Valle',x:.473,y:.683,description:'Al sur de Aethrion se extiende un valle fértil, atravesado por ríos y rodeado de bosque. Sus asentamientos encuentran refugio entre las elevaciones del Continente Central.',children:[],views:[view('arden','Valle de Arden · ríos y refugios')]},
 {id:'serynth',name:'Serynth',group:'central',type:'city',label:'Ciudad y región',x:.457,y:.786,description:'Serynth se encuentra entre montañas, bosques y un río que recorre el sur del continente. Sus torres de piedra se recortan frente a los paisajes más secos que anuncian Kael.',children:[],views:[view('serynth','Serynth · la ciudad entre montañas')]},
 {id:'colinas-vorlen',name:'Colinas de Vorlen',group:'central',type:'region',label:'Colinas',x:.563,y:.643,description:'Colinas, bosques y cursos de agua al este de Aethrion. Vorten se encuentra en esta región; hacia el sur, la vegetación cede lugar al Desierto de Kael.',children:['Vorten'],views:[view('vorlen','Vorlen · palacios y Aethrion al fondo'),view('vorlen-panorama','Vorten · panorama de las colinas')]},
 {id:'desierto-kael',name:'Desierto de Kael',group:'central',type:'danger',label:'Desierto',x:.582,y:.783,description:'Una península árida de arena, piedra y ruinas antiguas. Bajo las Ruinas de Kael permanece el rastro de Murmex, lejos de los bosques y las ciudades del norte.',children:['Ruinas de Kael','Murmex dormido'],views:[view('kael','Desierto de Kael · las ruinas')]},
 {id:'puerto-libar',name:'Puerto de Libar',group:'central',type:'city',label:'Puerto',x:.651,y:.602,description:'En la costa oriental, un pequeño puerto se reconoce por su gran palacio. Los muelles, las embarcaciones y el bosque cercano completan el paisaje de Libar.',children:['Palacio de Libar','Puerto pesquero'],views:[view('puerto-libar','Puerto de Libar · el palacio frente al mar')]},
 {id:'roca-guardian',name:'La Roca del Guardián',group:'central',type:'danger',label:'Cárcel de los Ecos Prohibidos',x:.354,y:.803,description:'Una roca gigantesca con una entrada custodiada. Lomira es el pequeño tramo de tierra unido a la roca; bajo ella se encuentra la cárcel de los Ecos Prohibidos.',children:['Lomira'],views:[view('guardian-lomira','La Roca del Guardián y Lomira')]},
 {id:'reino-kaeldor',name:'Reino de Kaeldor',group:'voranor',type:'city',label:'Reino',x:.121,y:.371,description:'El reino de Kaeldor se extiende entre las montañas y los bosques de Voranor, las Tierras del Ocaso. Sus torres oscuras dominan el paisaje del continente occidental.',children:[],views:[view('kaeldor','Kaeldor · el reino entre montañas')]},
 {id:'bosques-sombrales',name:'Bosques Sombrales',group:'voranor',type:'region',label:'Bosques',x:.097,y:.471,description:'Bosques densos bajo las montañas de Voranor. La bruma recorre las copas y abre, a lo lejos, pequeñas vistas hacia la costa.',children:[],views:[view('sombrales','Bosques Sombrales · entre niebla y montañas')]},
 {id:'islas-brumas',name:'Islas Brumas',group:'voranor',type:'region',label:'Archipiélago',x:.058,y:.558,description:'Frente a las costas de Voranor, las Islas Brumas aparecen entre la niebla y el oleaje del oeste. Sus islotes rocosos están cubiertos de vegetación.',children:[],views:[view('brumas','Islas Brumas · el archipiélago')]},
 {id:'reino-drakonia',name:'Reino de Drakonia',group:'thalkras',type:'city',label:'Reino',x:.15,y:.797,description:'El reino de piedra oscura de Thalkras ocupa un territorio de montañas y tierra ocre junto al mar. Más al sur, el paisaje se abre hacia las Llanuras Infinitas.',children:[],views:[view('drakonia','Drakonia · reino y costa')]},
 {id:'llanuras-infinitas',name:'Llanuras Infinitas',group:'thalkras',type:'region',label:'Llanuras',x:.221,y:.888,description:'Grandes extensiones abiertas de hierba dorada en las Tierras del Sur-Oeste. Las llanuras se prolongan hasta los acantilados y la costa de Thalkras.',children:[],views:[view('llanuras','Las Llanuras Infinitas al atardecer')]},
 {id:'reino-luxoria',name:'Reino de Luxoria',group:'elyndor',type:'city',label:'Reino',x:.849,y:.361,description:'En Elyndor, las Tierras del Amanecer, el Reino de Luxoria se alza entre montañas y colinas. Al este y al sur se extienden los bosques de Ysara y el territorio de la Montaña de Fuego.',children:[],views:[view('luxoria','Luxoria · el reino del Amanecer')]},
 {id:'selva-ysara',name:'Gran Selva de Ysara',group:'elyndor',type:'region',label:'Selva',x:.92,y:.481,description:'La gran selva cubre el este de Elyndor. Un paisaje de vegetación espesa y brumas que acompaña el relieve del continente hasta el mar.',children:[],views:[view('ysara','Ysara · la gran selva')]},
 {id:'montana-fuego',name:'Montaña de Fuego',group:'elyndor',type:'danger',label:'Volcán',x:.85,y:.558,description:'Un volcán junto a la costa meridional de Elyndor. Las laderas oscuras, la lava y el mar marcan el extremo de las Tierras del Amanecer.',children:[],views:[view('fuego','La Montaña de Fuego y su costa volcánica')]},
 {id:'reino-azzura',name:'Reino de Azzura',group:'solenia',type:'city',label:'Reino',x:.858,y:.781,description:'Azzura se alza sobre la costa de Solenia. Sus palacios claros miran al mar, mientras los caminos del interior llegan a montañas, bosques y valles.',children:[],views:[view('azzura','Azzura · los palacios de la costa')]},
 {id:'bosque-luminar',name:'Bosque de Luminar',group:'solenia',type:'region',label:'Bosque y lago',x:.765,y:.83,description:'Entre los bosques de Solenia se encuentra un único lago, rodeado de vegetación. La luz sobre el agua da identidad a este rincón de Luminar.',children:[],views:[view('luminar','Luminar · el lago en el bosque')]},
 {id:'tierras-heladas',name:'Tierras Heladas del Norte',group:'norte',type:'danger',label:'Región polar',x:.489,y:.14,description:'Al otro lado del Mar Glacial del Norte, las montañas nevadas y el hielo se extienden hasta el horizonte. Es el extremo frío del mundo conocido.',children:[],views:[view('tierras-heladas','Tierras Heladas · montañas y mar glacial')]},
 {id:'islas-tronox',name:'Islas de Tronox',group:'mares',type:'region',label:'Archipiélago',x:.66,y:.422,description:'Tronox Mayor y Tronox Menor se encuentran frente a la costa oriental del Continente Central. Sus construcciones se elevan entre islas, canales y aguas abiertas.',children:['Tronox Mayor','Tronox Menor'],views:[view('tronox','Tronox Mayor y Tronox Menor')]},
 {id:'islas-aureas',name:'Islas Áureas',group:'mares',type:'region',label:'Islas de comerciantes',x:.431,y:.938,description:'Pequeñas islas comerciales en el Mar del Sur, frente al Continente Central. Sus puertos conectan las rutas que recorren las costas de Cetrios.',children:[],views:[view('islas-aureas','Islas Áureas · puertos de comerciantes')]},
 {id:'mar-oeste',name:'Mar del Oeste',group:'mares',type:'danger',label:'Mar',x:.246,y:.51,description:'Entre Voranor y el Continente Central se abre el Mar del Oeste. Sus aguas profundas, costas rocosas y nieblas forman una frontera entre ambos territorios.',children:[],views:[view('mar-oeste','Mar del Oeste · aguas y costas lejanas')]}
 ];
 window.CETRIOS={groups,places,map:'assets/mapa.webp',version:'2026.09.09'};
})();
